# Generated by Django 3.1.3 on 2020-11-15 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=500, null=True)),
                ('excerpt', models.CharField(max_length=256, null=True)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(default='Uncategorized', null=True, to='blog.Category')),
                ('tags', models.ManyToManyField(default=None, null=True, to='blog.Tag')),
            ],
        ),
    ]
