# Generated by Django 3.1.3 on 2020-11-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201115_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='cats',
        ),
    ]
