# Generated by Django 3.1.3 on 2020-11-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201116_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
