# Generated by Django 3.1.3 on 2020-11-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201116_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.IntegerField(max_length=30)),
                ('subject', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('allowed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
