# Generated by Django 3.1.4 on 2020-12-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20201213_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image3',
            new_name='image2',
        ),
    ]
